version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: adcsa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ged_adcsa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - adcsa-network

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - adcsa-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - adcsa-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - adcsa-network

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/ged_adcsa
      - DB_USERNAME=admin
      - DB_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - adcsa-network

  backend:
    build: ./ged-adcsa-backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ged_adcsa
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    networks:
      - adcsa-network

  frontend:
    build: ./ged-adcsa-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - adcsa-network

volumes:
  pgdata:
  minio_data:
  elasticsearch_data:

networks:
  adcsa-network:
    driver: bridge
