-- Création de la table role
CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- Création de la table utilisateur
CREATE TABLE "utilisateur" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    statut VARCHAR(20) NOT NULL,
    derniere_connexion TIMESTAMP,
    date_creation TIMESTAMP NOT NULL,
    date_modification TIMESTAMP,
    date_expiration_token TIMESTAMP,
    date_verrouillage TIMESTAMP,
    tentatives_connexion INT DEFAULT 0,
    compte_verrouille BOOLEAN DEFAULT FALSE,
    token_reset_password VARCHAR(255),
    is_first_login BOOLEAN DEFAULT FALSE,
    password_changed_at TIMESTAMP,
    first_login_expires_at TIMESTAMP
);

-- Création de la table utilisateur_role (table de jointure)
CREATE TABLE utilisateur_role (
    utilisateur_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (utilisateur_id, role_id),
    FOREIGN KEY (utilisateur_id) REFERENCES "utilisateur"(id),
    FOREIGN KEY (role_id) REFERENCES role(id)
);

-- Création de la table password_reset_token
CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    utilisateur_id BIGINT NOT NULL,
    date_expiration TIMESTAMP NOT NULL,
    FOREIGN KEY (utilisateur_id) REFERENCES "utilisateur"(id)
);

-- Création de la table utilisateur_password_history
CREATE TABLE utilisateur_password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL,
    date_creation TIMESTAMP NOT NULL,
    FOREIGN KEY (utilisateur_id) REFERENCES "utilisateur"(id)
);

-- Création de la table refresh_token
CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    utilisateur_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (utilisateur_id) REFERENCES "utilisateur"(id)
); 